# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed35f81e5f132987a56ae273d8a5d1d15748ada83a2f818bc1ba2858d1eb1933a48bbe1124e786cc210c5b76b71ed640f67d93402667ff997158e4f486418d58

test:
  secret_key_base: 3c8480cbf4f6680cd259c7972224edc4c234dedb81dee965df52446c26b5ae6579e237084e1f8e57322faf22cd4f9d9481a0ed47ffd02f88125b3a9bf623a557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
